spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pnc_db
    username: User
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  profiles:
    active: local

app:
  jwt-secret: YlCuskBbIIZGteWW5JERcR30UAcXUG5fSKliGmGO70HGsjXzGZEnPkFUkHbZinWPL1Or96xJlEmogC2NpcwbHA
  jwt-access-expiration-milliseconds: 900000   # 15 minutes
  jwt-refresh-expiration-milliseconds: 604800000 # 7 days


